### ISSUE TITLE
Problem with back button not working

### ISSUE THREAD

**Issue by reggatta** [ltebean/LTNavigationBar#1]
Awesome code for a nice effect, thank you.  I have one problem where the back button does not work any longer when I navigate down a few layers.  Any idea what that could be?  It might be my code.

**Comment by ltebean** [comment]
The category inserts an overlay view to the navigationBar to achieve the effect. Once you call `[self.navigationController.navigationBar reset];`, the overlay view will be removed, everything should be back to normal. If you still have the problem, you can send me your code.

**Comment by reggatta** [comment]
Leo:

Thanks for getting back to me and I appreciate your writing the code.  I would like the user to be able to use the back button while keeping the clear effect on, but that may not be possible.  I’ll check it out some more and see if I can make it work.

Cheers,

Peter

On Feb 26, 2015, at 9:37 PM, Leo <notifications@github.com<mailto:notifications@github.com>> wrote:


The category inserts an overlay view to the navigationBar to achieve the effect. Once you call [self.navigationController.navigationBar reset];, the overlay view will be removed, everything should be back to normal. If you still have the problem, you can send me your code.

**Comment by xzenon** [comment]
Please see my Pull request #2 with the solution for given issue.

**Comment by reggatta** [comment]
Wow, that is an elegant fix!  I added my own code to position a clear button where the back button was and then got the navigation controller to pop the view.  I will put your new code in and see how that works. Thank you for working on this.

Cheers,

Peter


On Mar 5, 2015, at 2:52 PM, xZenon <notifications@github.com<mailto:notifications@github.com>> wrote:


Please see my Pull request #2<https://github.com/ltebean/LTNavigationBar/pull/2> with the solution for given issue.

**Comment by ltebean** [comment]
Thanks for the fix @xzenon 
I've submitted v1.0.1 with this fix

**Comment by reggatta** [comment]
I just tried your fix and it works great!  Thanks.

-Peter

On Mar 5, 2015, at 2:52 PM, xZenon <notifications@github.com<mailto:notifications@github.com>> wrote:


Please see my Pull request #2<https://github.com/ltebean/LTNavigationBar/pull/2> with the solution for given issue.
