### ISSUE TITLE
navigationBar自带的毛玻璃效果不见了？

### ISSUE THREAD

**Issue by Lilacxyz** [ltebean/LTNavigationBar#13]
tableview滚动上去，navigationbar颜色显示出来之后，navigationBar自带的毛玻璃效果貌似就没了……是因为和已有效果冲突么？

**Comment by ltebean** [comment]
是的目前的实现不支持毛玻璃效果

**Comment by TonyGJJ** [comment]
@ltebean 你好，请问什么时候能支持毛玻璃啊？
