### ISSUE TITLE
Add support for animated background color change 

### ISSUE THREAD

**Issue by TiagoVeloso** [ltebean/LTNavigationBar#14]
When using the `lt_setBackgroundColor`the color changes somewhat abruptly.

Ir would be awesome if the color could change in a smoother way with an animation.

**Comment by ltebean** [comment]
you can call the method in an animation block to achieve it:
```
[UIView animateWithDuration:3 animations:^{
    [self.navigationController.navigationBar lt_setBackgroundColor:[UIColor redColor]];
}];
```

**Comment by TiagoVeloso** [comment]
Cool tks.
