### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by iTofu** [ltebean/LTNavigationBar#28]
当我在 `AppDelegate.m` 中调用了如下代码：

````objc
[[UINavigationBar appearance] setBackgroundImage:[UIImage imageNamed:@"navBg"]
                                  forBarPosition:UIBarPositionTopAttached
                                      barMetrics:UIBarMetricsDefault];
````

LCNavigationBar 就会失效，如下图：
![simulator](https://cloud.githubusercontent.com/assets/10044430/14421503/9a5e9fc6-0004-11e6-80a3-54754fc49c26.png)

**Comment by iTofu** [comment]
navBg:
![navbg 2x](https://cloud.githubusercontent.com/assets/10044430/14421602/20433f7a-0005-11e6-8b19-92ff2100671a.png)

**Comment by langhua9527** [comment]
[[UINavigationBar appearance]setBarTintColor:[UIColor clearColor]]; 你可以这样全局设置一下
