### ISSUE TITLE
[Question] set LTNavigationBar only for detailViewControler

### ISSUE THREAD

**Issue by iamchenchen** [ltebean/LTNavigationBar#3]
From my test, seems like it can only do the first view controller.

**Comment by ltebean** [comment]
It should work in any view controller in the navigation controller hierarchy.
Could you send me your test code so that I can find what's wrong with it.

**Comment by iamchenchen** [comment]
@ltebean thanks for your fast reply.  Here is my gist code: https://gist.github.com/iamchenchen/98ad05eb9415c33a3047

The profileController is a detailviewController from a tableviewController.

Thanks for your help!

**Comment by iamchenchen** [comment]
@ltebean I actually fix the problem by removing code below.  It's my bad, thanks!

```
//    [[UINavigationBar appearance] setShadowImage:[UIImage new]];
//    [[UINavigationBar appearance] setBackgroundImage:[UIImage new] forBarMetrics:UIBarMetricsDefault];
```
