### ISSUE TITLE
如何做到仅仅动态改变背景的alpha,不改变导航栏上的其他控件的alpha

### ISSUE THREAD

**Issue by greezi** [ltebean/LTNavigationBar#34]
急求...

**Comment by ltebean** [comment]
调用 lt_setBackgroundColor
不要调用 lt_setElementsAlpha

**Comment by greezi** [comment]
好像问得不对,应该是默认让他显示导航栏上的所有子控件,上滑的时候改变导航栏的透明度就好,从始至终不改变子控件的alpha

**Comment by langhua9527** [comment]
[[UINavigationBar appearance]setBarTintColor:[UIColor clearColor]]; 你可以这样全局设置一下
