### ISSUE TITLE
iOS 10 Navigation bar is not set to transparent

### ISSUE THREAD

**Issue by Pratik948** [ltebean/LTNavigationBar#40]
I am writing code for app with future support so basically i'm looking at all side previous versions, current version, as well as future version which will be iOS 10.

This category works perfect until iOS 9.3.3 but in iOS 10 its not working, i've tested on both iDevice and Simulator

I'm setting clear colour for navigation bar at `viewDidLoad` as below

`  [self.navigationController.navigationBar setShadowImage:[UIImage new]];
    [self.navigationController.navigationBar lt_setBackgroundColor:[UIColor clearColor]];
`

Please someone help me out with this.

I'm sorry for my english, i don't know what language you're using 😜

Thanks.

**Comment by XiangNanLi** [comment]
I have the same question.
I find that the "_NavigationBarBackground" is under the overlay view at iOS 10, but the "_UIBarBackground" is above the overlay view at iOS 9.3.3.
When push to new ViewController , the overlay view is at the front of the navigationbar.
I just set the backgroundColor.

**Comment by ltebean** [comment]
fixed in v2.1.3

**Comment by Pratik948** [comment]
thanks for the new version 👍
