### ISSUE TITLE
Height of NavigationBar is larger after update.

### ISSUE THREAD

**Issue by HiroshiHorie** [ltebean/LTNavigationBar#42]
The NavigationBar height gets about +20 pixels larger after update on all NavigationBars.

**Comment by brotmanm** [comment]
In - (void)lt_setBackgroundColor:(UIColor *)backgroundColor delete the + 20 when the overlays frame is set in the initialization statement.

**Comment by HiroshiHorie** [comment]
Thanks, but when will this be fixed in the repo ? because anytime updating the pod overwrites the code back again.

**Comment by ltebean** [comment]
fixed in v2.1.4
