### ISSUE TITLE
When the device version is less than 10.0, the navigationBar display heighter.

### ISSUE THREAD

**Issue by XiangNanLi** [ltebean/LTNavigationBar#43]
I saw the code , when the version is less than 10.0, the overlay 's height is heighter 20 than before.
`
if (SYSTEM_VERSION_LESS_THAN(@"10.0")) {
            self.overlay = [[UIView alloc] initWithFrame:CGRectMake(0, -20, CGRectGetWidth(self.bounds), CGRectGetHeight(self.bounds) + 20)];
        } else {
            self.overlay = [[UIView alloc] initWithFrame:CGRectMake(0, 0, CGRectGetWidth(self.bounds), CGRectGetHeight(self.bounds) + 20)];
        }
`

**Comment by ltebean** [comment]
fixed in v2.1.5
