### ISSUE TITLE
On rotate background image error ios7

### ISSUE THREAD

**Issue by CoreteamEU** [ltebean/LTNavigationBar#5]
The same error with wrong background size on device rotation.
On ios8 everything is ok, error is on ios7.

**Comment by ltebean** [comment]
I've tested on 7.0.3 simulator and it works fine, can you give me the specific version where you got the error

**Comment by CoreteamEU** [comment]
This is wierd.
So, I compiled for 4S, ios7.1.2. Worked fine.
Then I imidiately run on ipad2 7.1.2, then artefacts (in attachment).
Then I clean project. All errors gone.
I rebuilt on 4S, run on ipad2, no errors. It is gone. So... I wonder :)
