### ISSUE TITLE
滑动隐藏导航栏后下拉显示时返回箭头不见了

### ISSUE THREAD

**Issue by ChinaFanny** [ltebean/LTNavigationBar#55]
当navigationcontroller执行 push操作后，返回按钮是系统的，滑动隐藏导航栏后下拉显示时返回箭头不见了，如下图，请问这个是怎么回事，如何修改呢？谢谢～～～
<img width="463" alt="qq20161221-180913 2x" src="https://cloud.githubusercontent.com/assets/22438061/21385434/81cd9210-c7a9-11e6-8deb-6622a8b4d230.png">
<img width="459" alt="qq20161221-180935 2x" src="https://cloud.githubusercontent.com/assets/22438061/21385439/82f6acee-c7a9-11e6-9126-69ca1e742681.png">
<img width="466" alt="qq20161221-180946 2x" src="https://cloud.githubusercontent.com/assets/22438061/21385436/825c6440-c7a9-11e6-93d9-83956c551192.png">

**Comment by ChinaFanny** [comment]
在lt_setElementsAlpha方法中，修改“obj.alpha = obj.alpha == 0 ? 0 : alpha”语句为“obj.alpha = alpha”， 可以解决我上述提到的问题，望作者采纳解决～
`- (void)lt_setElementsAlpha:(CGFloat)alpha
{
    [[self valueForKey:@"_leftViews"] enumerateObjectsUsingBlock:^(UIView *view, NSUInteger i, BOOL *stop) {
        view.alpha = alpha;
    }];
    
    [[self valueForKey:@"_rightViews"] enumerateObjectsUsingBlock:^(UIView *view, NSUInteger i, BOOL *stop) {
        view.alpha = alpha;
    }];
    
    UIView *titleView = [self valueForKey:@"_titleView"];
    titleView.alpha = alpha;
//    when viewController first load, the titleView maybe nil
    [[self subviews] enumerateObjectsUsingBlock:^(UIView *obj, NSUInteger idx, BOOL *stop) {
        if ([obj isKindOfClass:NSClassFromString(@"UINavigationItemView")]) {
            obj.alpha = alpha;
        }
        if ([obj isKindOfClass:NSClassFromString(@"_UINavigationBarBackIndicatorView")]) {
            //
            // Modified by ChinaFanny
            // (解决push一个controller后，滑动隐藏导航后再滑动显示时返回按钮<系统自带返回按钮>的箭头消失问题)
            //
            
//            obj.alpha = obj.alpha == 0 ? 0 : alpha;
            **obj.alpha = alpha;**
        }
    }];
}`

**Comment by ChinaFanny** [comment]
在lt_setElementsAlpha方法中，修改“obj.alpha = obj.alpha == 0 ? 0 : alpha”语句为“obj.alpha = alpha”， 可以解决我上述提到的问题，望作者采纳解决～
`- (void)lt_setElementsAlpha:(CGFloat)alpha
{
    [[self valueForKey:@"_leftViews"] enumerateObjectsUsingBlock:^(UIView *view, NSUInteger i, BOOL *stop) {
        view.alpha = alpha;
    }];
    
    [[self valueForKey:@"_rightViews"] enumerateObjectsUsingBlock:^(UIView *view, NSUInteger i, BOOL *stop) {
        view.alpha = alpha;
    }];
    
    UIView *titleView = [self valueForKey:@"_titleView"];
    titleView.alpha = alpha;
//    when viewController first load, the titleView maybe nil
    [[self subviews] enumerateObjectsUsingBlock:^(UIView *obj, NSUInteger idx, BOOL *stop) {
        if ([obj isKindOfClass:NSClassFromString(@"UINavigationItemView")]) {
            obj.alpha = alpha;
        }
        if ([obj isKindOfClass:NSClassFromString(@"_UINavigationBarBackIndicatorView")]) {
            //
            // Modified by ChinaFanny
            // (解决push一个controller后，滑动隐藏导航后再滑动显示时返回按钮<系统自带返回按钮>的箭头消失问题)
            //
            
//            obj.alpha = obj.alpha == 0 ? 0 : alpha;
            obj.alpha = alpha;
        }
    }];
}`

**Comment by ChinaFanny** [comment]
`- (UIView *)overlay
{
    return objc_getAssociatedObject(self, &overlayKey);
}

- (void)setOverlay:(UIView *)overlay
{
    objc_setAssociatedObject(self, &overlayKey, overlay, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}

- (void)lt_setBackgroundColor:(UIColor *)backgroundColor
{
    if (!self.overlay) {
        [self setBackgroundImage:[UIImage new] forBarMetrics:UIBarMetricsDefault];
        self.overlay = [[UIView alloc] initWithFrame:CGRectMake(0, 0, CGRectGetWidth(self.bounds), CGRectGetHeight(self.bounds) + 20)];
        self.overlay.userInteractionEnabled = NO;
        self.overlay.autoresizingMask = UIViewAutoresizingFlexibleWidth;    // Should not set `UIViewAutoresizingFlexibleHeight`
        
        [[self.subviews firstObject] insertSubview:self.overlay atIndex:self.subviews.count -1];
    }
    self.overlay.backgroundColor = backgroundColor;
}

- (void)lt_setTranslationY:(CGFloat)translationY
{
    self.transform = CGAffineTransformMakeTranslation(0, translationY);
}

- (void)lt_setElementsAlpha:(CGFloat)alpha
{
    [[self valueForKey:@"_leftViews"] enumerateObjectsUsingBlock:^(UIView *view, NSUInteger i, BOOL *stop) {
        view.alpha = alpha;
    }];
    
    [[self valueForKey:@"_rightViews"] enumerateObjectsUsingBlock:^(UIView *view, NSUInteger i, BOOL *stop) {
        view.alpha = alpha;
    }];
    
    UIView *titleView = [self valueForKey:@"_titleView"];
    titleView.alpha = alpha;
    //    when viewController first load, the titleView maybe nil
    [[self subviews] enumerateObjectsUsingBlock:^(UIView *obj, NSUInteger idx, BOOL *stop) {
        if ([obj isKindOfClass:NSClassFromString(@"UINavigationItemView")]) {
            obj.alpha = alpha;
            *stop = YES;
        }
    }];
}

- (void)lt_reset
{
    [self setBackgroundImage:nil forBarMetrics:UIBarMetricsDefault];
    [self.overlay removeFromSuperview];
    self.overlay = nil;
}`

**Comment by ltebean** [comment]
fixed in v2.1.9
