### ISSUE TITLE
问题多多哦 

### ISSUE THREAD

**Issue by wff-** [ltebean/LTNavigationBar#61]

**Comment by ltebean** [comment]
This lib uses a hacky way to achieve the result, in the new iOS version, the structure of UINavigation is changed and this lib no longer works anymore, so please check these alternatives:

https://github.com/andreamazz/AMScrollingNavbar
https://github.com/DanisFabric/RainbowNavigation
https://github.com/MoZhouqi/KMNavigationBarTransition
