### ISSUE TITLE
Crashed on iOS11

### ISSUE THREAD

**Issue by wujianbotju** [ltebean/LTNavigationBar#62]
I used a single UINavigationBar(NOT UINavigationController), App crashed on lt_setBackgroundColor method. It seems that UINavigationBar subviews structure has changed.

**Comment by D-meng** [comment]
xcode9   iOS11 

 Trapped uncaught exception 'NSUnknownKeyException', reason: '[<UINavigationBar 0x7f828ee04ac0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _titleView.'

**Comment by ltebean** [comment]
This lib uses a hacky way to achieve the result, in the new iOS version, the structure of UINavigation is changed and this lib no longer works anymore, so please check these alternatives:

https://github.com/andreamazz/AMScrollingNavbar
https://github.com/DanisFabric/RainbowNavigation
https://github.com/MoZhouqi/KMNavigationBarTransition

**Comment by noodles1024** [comment]
Yeah, I know that the structure of UINavigation is changed in the new iOS version.
So you won't continue to update this lib? So sad...
Anyway, thank you, bro, for cool LTNavigationBar
