### ISSUE TITLE
iOS 11 崩溃

### ISSUE THREAD

**Issue by boai** [ltebean/LTNavigationBar#64]
LTNavigationBar[11369:4642197] [Accessibility] ****************** Loading GAX Client Bundle ****************
2017-06-28 14:30:40.795882+0800 LTNavigationBar[11369:4642197] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UINavigationBar 0x1039250a0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _leftViews.'
*** First throw call stack:
(0x186ed9858 0x1856b0528 0x186ed9520 0x187a26e88 0x18796ceac 0x10367efc0 0x10367e05c 0x10367de80 0x18d9e000c 0x19d4e7f00 0x18d705b5c 0x18d7ab6c0 0x18d871a0c 0x18dd49978 0x18dd4df1c 0x18d862b9c 0x18d7181f4 0x18dd38364 0x18dd37f24 0x18dd37080 0x18d7164f4 0x18d6e7b38 0x19d4af210 0x18dfe9514 0x18dfeb984 0x18dfe4af0 0x186e80528 0x186e7fe0c 0x186e7d904 0x186d9c280 0x1888adf94 0x18d74b0f0 0x10367ea80 0x185b8de40)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ltebean** [comment]
This lib uses a hacky way to achieve the result, in the new iOS version, the structure of UINavigation is changed and this lib no longer works anymore, so please check these alternatives:

https://github.com/andreamazz/AMScrollingNavbar
https://github.com/DanisFabric/RainbowNavigation
https://github.com/MoZhouqi/KMNavigationBarTransition

**Comment by nadagamal** [comment]
Hi,
Do you solve this issue ?

Thank you
