### ISSUE TITLE
iOS11，UINavigationBar拿不到self.subviews了，如何解决？

### ISSUE THREAD

**Issue by WenkyYuan** [ltebean/LTNavigationBar#68]
[[self.subviews firstObject]  insertSubview:self.overlay atIndex:0];

这样insert没用了。

**Comment by ltebean** [comment]
This lib uses a hacky way to achieve the result, in the new iOS version, the structure of UINavigation is changed and this lib no longer works anymore, so please check these alternatives:

https://github.com/andreamazz/AMScrollingNavbar
https://github.com/DanisFabric/RainbowNavigation
https://github.com/MoZhouqi/KMNavigationBarTransition
