### ISSUE TITLE
Parallax Effect for the Header View

### ISSUE THREAD

**Issue by confile** [ltebean/LTNavigationBar#8]
Could you integrate a Parallax effect like in this lib: 

https://github.com/JackTeam/PathCover

I think this would look great with your awesome lib.

**Comment by ltebean** [comment]
I demonstrated how to make this effect in the 'parralax' branch, generally, in scrollViewDidScroll,  you can apply transform to the target view to achieve various effects

**Comment by confile** [comment]
thanks!
